### ISSUE TITLE
Sample "microphone" doesn't work

### ISSUE THREAD

**Issue by SirDev** [Microsoft/Cognitive-Speech-STT-JavaScript#11]
I've tried using this demo to implement a proof of concept with voice recognizition on one of our search portals.

This sample is either borked or something else is going on:

- Long-text is not available
- Microphone recordings don't seem to send to the server
- All I get is "The weather is nice"

Issues on Chrome Version 52.0.2743.116 m (64-bit)

**Comment by greuterc** [comment]
same here, i was unable to get the mic sample to work. I followed the instructions in the readme. when not using the mic, the sample wav is sent and i see a response, but with mic nothing happens.

tested with Microsoft Edge and Chrome

**Comment by antogh** [comment]
and +2, same here, exactly same problem described by the two users above. The sample works with the MIC disabled and converts the wav file to "The weather is nice" , but with the MIC on there is no conversion, chrome on win10, chrome on android or edge on win10, same problem. I have seen with the debugger that startMicAndRecognition is called and the browser asks permission to use the microphone, then after 5 seconds endMicAndRecognition also is called , so the logic works in some way, the problem is I cannot see any network activity between these two calls, so I assume no data is sent to the cloud and consequently the onPartialResponseReceived / onFinalResponseReceived events collecting the converted text are never called. 
It must be something simple missing like maybe a version mismatch, but it's a pity that no one cares to fix this issue in 2 MONTHS (it's not the same Microsoft I used to know...) . There is a similar API from Google, I will look at that now.

**Comment by SirDev** [comment]
I wanted to use this for a proof of concept showing our clients the possibilities of Microsofts' new cognitive services (it's a great business case after all) but I wasn't able to demo. Client was dissappointed because we made a promise. Anyway. Hope Microsoft fixes this.

**Comment by antogh** [comment]
Similar situation here. 
I guess it's just the javascript api or this sample that have problems. But I need to create a web app not a native app so I need the javascript api to work.
Look at the sample at the bottom of this page, work sooo fine with any browser, even on smartphones...
https://www.microsoft.com/cognitive-services/en-us/speech-api
it would be nice to be able to create a page like that.
Just for curiosity I have tried to replace the content of the whatstheweatherlike.wav with something I recorded from my microphone like "this is a test" . I left the audio file with same sample rate , wav format and even the number of bytes is identical, the audio data goes to the cloud endpoint and the error callback is called in return with the message "received a speech error -1" 
Looks like this API is really picky

**Comment by beeva-manuelfranco** [comment]
I have experienced the same problem. I have tried with Chrome, Edge and Firefox. MIC example doesn't work

**Comment by priyaravi20** [comment]
Thank you all for the feeback. I wanted to update that we have started investigation and initial findings do point to cases where the sdk sample is failing if there is a delay in user utterance after Mic is opened. I will post as soon as we fix the sample.

**Comment by jasonvomsft** [comment]
This issue has been addressed in commit a99cec8c8813269ce9cf2bfd87d403d5c42bcd70.
